ci: add a macOS build CI action
Add a macOS build job to build the Release configuration..

Fix the autoconf script to pass through unknown CPU architectures. The
GitHub macOS builder ends up with an architecture of "i486", which is
weird, but it only matters that we have something.

Set the macOS deplopyment target. Otherwise, we end up building a
version of dceidl that can't acrually run on the host OS version.

Signed-off-by: James Peach <jpeach@apache.org>

diff --git a/BuildConfig/run-autoconf b/BuildConfig/run-autoconf
--- a/BuildConfig/run-autoconf
+++ b/BuildConfig/run-autoconf
@@ -37,8 +37,13 @@ set -e
 
 error()
 {
-    echo "$PROG: error: " "$@" 1>&2
+    echo "$PROG: error:" "$@" 1>&2
     exit 1
+}
+
+warn()
+{
+    echo "$PROG: warning:" "$@" 1>&2
 }
 
 message()
@@ -50,10 +55,13 @@ message()
 # x86_64 hosts.
 architecture()
 {
-    case $(machine) in
+    local m="$(machine)"
+    case $m in
         i386) echo i386 ;;
         x86_64|x86_64h) echo x86_64 ;;
-        *) echo unknown ;;
+        *)
+            warn "unexpected machine type \"$m\""
+            echo "$m" ;;
     esac
 }
 
@@ -68,7 +76,7 @@ detect_sdk_arch()
 
     # Get the list of archs that the SDK compiler will be able to
     # link
-    local archs=$(xcrun lipo -info ${crt1} | awk -F: '{print $3}')
+    local archs="$(xcrun lipo -info ${crt1} | awk -F: '{print $3}')"
 
     # If the SDK supports our native arch, prefer to use that.
     for arch in $archs ; do
@@ -125,16 +133,17 @@ configure_is_required()
     return 1
 }
 
-PROG=$(basename $0)
-SRCROOT=${SRCROOT:=$(cd $(dirname $0)/.. && pwd)}
-SDKROOT=${SDKROOT:-/}
-SDKARCH=$(detect_sdk_arch)
+PROG="$(basename $0)"
+SRCROOT="${SRCROOT:=$(cd $(dirname $0)/.. && pwd)}"
+SDKROOT="${SDKROOT:-/}"
+SDKARCH="$(detect_sdk_arch)"
 
 cd "${SRCROOT}/dcerpc" || error "${SRCROOT}/dcerpc" has gone AWOL
 
 message SRCROOT is $SRCROOT
 message SDKROOT is $SDKROOT
 message SDK architecture is $SDKARCH
+message host architecture is $(architecture)
 
 if autoreconf_is_required ; then
     message "running autoreconf"
@@ -154,11 +163,12 @@ esac
 
 if configure_is_required ; then
     message "running configure"
+    set -x
     ./configure \
-	--host=$SDKARCH-apple-darwin$(uname -r) \
-	--build=$(architecture)-apple-darwin$(uname -r) \
-	CC=$(xcrun -find cc) \
-	CXX=$(xcrun -find c++) \
+	--host="$SDKARCH-apple-darwin$(uname -r)" \
+	--build="$(architecture)-apple-darwin$(uname -r)" \
+	CC="$(xcrun -find cc)" \
+	CXX="$(xcrun -find c++)" \
 	CFLAGS="-arch $SDKARCH -isysroot $SDKROOT" \
 	CXXFLAGS="-arch $SDKARCH -isysroot $SDKROOT" \
         FLEX="$(brew --prefix flex)/bin/flex" \
@@ -173,3 +183,5 @@ if configure_is_required ; then
 else
     message "config.status exists, skipping configure phase"
 fi
+
+# vim: set ts=8 :
